/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Item } from "./components/colorman-parent/colorman-parent";
export namespace Components {
    interface ColormanList {
        "itemsList": Item[];
        "loading": boolean;
    }
    interface ColormanListitem {
        "description": string;
        "name": string;
    }
    interface ColormanParent {
        /**
          * App ID
         */
        "appId": string;
        /**
          * Bundle ID
         */
        "bundleId": string;
    }
    interface ColormanSearch {
        "searchQuery": string;
    }
}
declare global {
    interface HTMLColormanListElement extends Components.ColormanList, HTMLStencilElement {
    }
    var HTMLColormanListElement: {
        prototype: HTMLColormanListElement;
        new (): HTMLColormanListElement;
    };
    interface HTMLColormanListitemElement extends Components.ColormanListitem, HTMLStencilElement {
    }
    var HTMLColormanListitemElement: {
        prototype: HTMLColormanListitemElement;
        new (): HTMLColormanListitemElement;
    };
    interface HTMLColormanParentElement extends Components.ColormanParent, HTMLStencilElement {
    }
    var HTMLColormanParentElement: {
        prototype: HTMLColormanParentElement;
        new (): HTMLColormanParentElement;
    };
    interface HTMLColormanSearchElement extends Components.ColormanSearch, HTMLStencilElement {
    }
    var HTMLColormanSearchElement: {
        prototype: HTMLColormanSearchElement;
        new (): HTMLColormanSearchElement;
    };
    interface HTMLElementTagNameMap {
        "colorman-list": HTMLColormanListElement;
        "colorman-listitem": HTMLColormanListitemElement;
        "colorman-parent": HTMLColormanParentElement;
        "colorman-search": HTMLColormanSearchElement;
    }
}
declare namespace LocalJSX {
    interface ColormanList {
        "itemsList"?: Item[];
        "loading"?: boolean;
    }
    interface ColormanListitem {
        "description"?: string;
        "name"?: string;
    }
    interface ColormanParent {
        /**
          * App ID
         */
        "appId"?: string;
        /**
          * Bundle ID
         */
        "bundleId"?: string;
    }
    interface ColormanSearch {
        "onColormanQueryChange"?: (event: CustomEvent<any>) => void;
        "searchQuery"?: string;
    }
    interface IntrinsicElements {
        "colorman-list": ColormanList;
        "colorman-listitem": ColormanListitem;
        "colorman-parent": ColormanParent;
        "colorman-search": ColormanSearch;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "colorman-list": LocalJSX.ColormanList & JSXBase.HTMLAttributes<HTMLColormanListElement>;
            "colorman-listitem": LocalJSX.ColormanListitem & JSXBase.HTMLAttributes<HTMLColormanListitemElement>;
            "colorman-parent": LocalJSX.ColormanParent & JSXBase.HTMLAttributes<HTMLColormanParentElement>;
            "colorman-search": LocalJSX.ColormanSearch & JSXBase.HTMLAttributes<HTMLColormanSearchElement>;
        }
    }
}
